import tkinter as tk
root = tk.Tk()
# root.title("demo window")
# root.geometry("400x300")
# root.config(bg="black")
# root.mainloop()
def get_user():
    i = entry.get()
    label.config(text = f"Hey There {i} " , bg = "black" , fg = "red" )
root.title("welcome")
root.geometry("400x300")
root.config(bg = "black")
entry = tk.Entry(root , bg = "white" , width=30 , fg = "black")
entry.pack()
label = tk.Label(root  , bg="black")
label.pack()
button = tk.Button(root , bg = "yellow" , fg = "black" , text="PRESS ME!" , command = get_user , width=20)
button.pack()
root.mainloop()